name: Hestia
on: [push]
jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build -v .

    - name: Test Main
      run: go test ./ -coverprofile=coverage.txt -covermode=atomic
    
    - name: Test Models
      env:
        FIREBASE_CRED: ${{ secrets.FIREBASE_CRED }}
      run: go test ./models -coverprofile=models/coverage.txt -covermode=atomic
    
    - name: Test Controllers
      env:
        FIREBASE_CRED: ${{ secrets.FIREBASE_CRED }}
      run: go test ./controllers -coverprofile=controllers/coverage.txt -covermode=atomic
    
    - name: Merge Coverage Profiles
      run: |
        sed '1d' ./config/coverage.txt >> ./coverage.txt &&
        sed '1d' ./models/coverage.txt >> ./coverage.txt &&
        sed '1d' ./controllers/coverage.txt >> ./coverage.txt

    - uses: codecov/codecov-action@v1.0.2
      with:
        file: ./coverage.txt
        token: ${{secrets.CODECOV_TOKEN}}
